version: '3.8'

services:
  base_datos:
    image: mysql:8.0
    container_name: contenedor_bd_ticketpro
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - volumen_datos_mysql:/var/lib/mysql
      - ./ticketpro.sql:/docker-entrypoint-initdb.d/01-ticketpro.sql

  aplicacion_spring:
    build: .
    container_name: contenedor_app_ticketpro
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: base_datos
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - base_datos

volumes:
  volumen_datos_mysql:
