spring.application.name=ticketpro
# Configuración de la conexión a la Base de Datos 
# Utilizamos puerto 3306 porque es la OFICIAL de Mysql.
#Ponemos este código para que VS sepa si estoy en el docker o no

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${MYSQL_DB_NAME:ticketpro}
spring.datasource.username=${MYSQL_ROOT_USER:root}
spring.datasource.password=${MYSQL_ROOT_PASSWORD:Holahola123.}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate actualiza el esquema sin borrar datos existentes (vital para persistencia en Docker/AWS)
spring.jpa.hibernate.ddl-auto=update

# Forzar a Thymeleaf a que no guarde caché (así si cambiamos un HTML, se actualiza al recargar la web)
spring.thymeleaf.cache=false