spring.application.name=ticketpro
# Configuración de la conexión a la Base de Datos 
# Utilizamos puerto 3306 porque es la OFICIAL de Mysql.
#Ponemos este código para que VS sepa si estoy en el docker o no

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/ticketpro 
spring.datasource.username=root
spring.datasource.password=Holahola123.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Forzar a Thymeleaf a que no guarde caché (así si cambiamos un HTML, se actualiza al recargar la web)
spring.thymeleaf.cache=false